# config_params.yaml
random_forest:
  n_estimators: 100           # Number of trees in the forest
  max_depth: null             # Maximum depth of the tree (null means no limit)
  min_samples_split: 2        # Minimum number of samples required to split an internal node
  random_state: 8888          # Random state for reproducibility
  # Add any other parameters as needed for experimentation

decision_tree:
  criterion: gini,   # Default, you can change this to "entropy" if needed
  max_depth": 10,       # Limit the depth of the tree
  random_state: 8888

  